name: datomico
channels:
  - featuretools
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - dask
  - featuretools
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - matplotlib
  - numpy
  - numpy-base
  - pandas
  - pathlib
  - pillow
  - pip
  - pyqt
  - python=3.6.8
  - tqdm
  - widgetsnbextension
